server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite::resource:db/mockdata.db
    username:
    password:
    driver-class-name: org.sqlite.JDBC
    type: org.sqlite.SQLiteDataSource
  jpa:
    properties:
      database: mysql
      show-sql: true
      database-platform: com.springboot.sqlite.SQLDialect